### ISSUE TITLE
Counts data are not integers

### ISSUE THREAD

**Issue by sumeetpalsingh** [hyunhwaj/SalmonTE#23]
Thanks for developing the SalmonTE tool. It is working wonderfully even on my humble laptop. Just as comparison, I could not run any other TE counting tool as they all needed STAR, and I do not have a server or a machine with 32 Gb RAM.

I have one question on the output file. I see that the count data is not integer. I get decimal values. Could you please explain how 'counts' are generated. 

I am asking this as I have the count data for genes for the files, and I was thinking about adding them to the gene count. Is is possible/ok to concatenate the counts obtained from SalmonTE to gene counts obtained from HT-Seq mapping -> featureCounts.

Also, does SalmonTE only map a fraction of the reads, or all of them. This is again so that I understand how to add TE counts to gene counts, and perform correlation analysis and such.

Thanks!

**Comment by hyunhwaj** [comment]
Dear @sumeetpalsingh,

1. SalmonTE uses [Salmon](https://github.com/COMBINE-lab/salmon), as a core algorithm of the quantification. [It *estimates* read counts](https://salmon.readthedocs.io/en/latest/file_formats.html#quantification-file), so it is possible to have non-integer numbers as the read counts. Based on my experience it is okay if you *round* the non-integer numbers for the further analysis.

2. Regarding the concatenation, the question was initiated by several people, but I did not have any chance to answer the question in the Github so far. My answer is - it depends on what you did for gene-level quantification and what you will do with the data. I honestly did not perform any experiment regarding this matter, but it is not frequent you observe TEs are within exon-region or UTR-region when you observe random genes (it is my random, and can be biased). So, if you count "gene sequences (exon + intron)", not transcriptome, then this may count intron regions, so it may be not a great idea to concatenate genes and TEs. Otherwise, if you only count reads within exon regions for gene/isoform counting then, I think the concatenation will be okay.

3. Again, the count is *estimated counts* and when you map the "all reads" to the TEs.

Best Regards,

Hyun-Hwan Jeong
