### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by wjyzidane** [hyunhwaj/SalmonTE#5]
I noticed there are two reference options. one is hs and another is dm. Are they for human and mouse?

**Comment by hyunhwaj** [comment]
Yes, you're correct.

**Comment by wjyzidane** [comment]
I see. Is that possible there is a version for the mouse in the future?

**Comment by hyunhwaj** [comment]
Hello @wjyzidane, 

It should be possible, and there are several requests for adding and customization of the new reference. I will start to work on adding the mouse reference in the next week and will let you know once it has been done. Please let me know if you have any additional request.

Thank you,

Hwan

**Comment by wjyzidane** [comment]
Thanks so much! It would be very helpful!

**Comment by hyunhwaj** [comment]
Hello @wjyzidane,

Please allow me a week more to add the reference. I do not have any chance to work on it because I have to spend a couple of days for a trip, and I was back to my town yesterday.

Thank you,

Hwan

**Comment by wjyzidane** [comment]
No problem. Thanks for letting me know!

Jingyi

**Comment by adomingues** [comment]
Hi @hyunhwaj,

thank for developing this tool - I am very much looking forward to test it on my data.

Regarding the references, I was wondering if you could provided some more detailed guidelines on how to produce them, expanding on your answer [here](https://github.com/hyunhwaj/SalmonTE/issues/3#issuecomment-354519806) instead of producing all the indexes for the species we (users) need. Simple repeats and DNA elements should be easy enough to identify and remove from the repBase annotations. Would it affect too much the quantification if repeat genes are kept?

 I am working on Zebrafish, and it feels too much of an ask for you produce the index for me. Of course if you are willing to do it, I am happy to use them :)

**Comment by hyunhwaj** [comment]
Dear @wjyzidane and @adomingues, 

As you wished, I have created references for mouse and zebrafish. Please re-download the tool (or pull the latest version of `git`) to use them. I also created [a document](https://github.com/hyunhwaj/SalmonTE/wiki/How-to-build-a-customized-index) which introduces how to create a customized reference index. Please feel free to report if you find anything is wrong inside this document. You can use `mm` (for mouse) and `dr` (for zebrafish) as the value of `--ref_name` parameter in `quant` mode.

To @adomingues,

> Simple repeats and DNA elements should be easy enough to identify and remove from the repBase annotations. Would it affect too much the quantification if repeat genes are kept?

I think I don't have a straightforward answer to the question, and I feel I can give you an answer of the question if I have a benchmark between different two different references (with/without simple repeat). I believe the key to the answer will be how **simple repeats** repeats on the other repeat elements. For the further experiments, I will not give you answer in this month (due to another project), but I hope I can give you the answer in this February or March. I will appreciate if you report me the answer.

Best Regards,

Hyun-Hwan Jeong

**Comment by adomingues** [comment]
That was fast. Thank you @hyunhwaj!

> simple repeats

Maybe I didn't phrase it well, but I was more concerned about repeated genes which (i) maybe harder to identify, and (ii) are relatively common in Zebrafish. Simple repeats I agree that removing them is best, since the quantification of their expression is not very informative  anyway (not that I am aware of).

Once again thank you and I will report back in a week or so when I analyse my new data.

**Comment by hyunhwaj** [comment]
You're welcome, @adomingues,

For me, it must be exciting I to perform SalmonTE for Zebrafish data. Could you introduce a nice RNA-Seq dataset to play? I also will appreciate you show an example "repeated genes" for Zebrafish. 

Thank you,

Hyun-Hwan Jeong

**Comment by wjyzidane** [comment]
Thanks Hyum-Hwan! I would give it a try!

Jingyi

**Comment by adomingues** [comment]
> I also will appreciate you show an example "repeated genes" for Zebrafish.

Before the example, and in case you are not aware of, the teleost genome (Zebrafish) went through an ancient duplication during evolution ([1](https://www.zfin.org/ZDB-LAB-970408-67), [2](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC313070/)) which means their genome is little strange :) 

As for examples, _tdrd6_ has three copies (here named a-c to make things easy):

- [Tdrd6a (Chr20)](http://www.ensembl.org/Danio_rerio/Transcript/ProteinSummary?db=core;g=ENSDARG00000070052;r=20:35545080-35561392;t=ENSDART00000102504 )

- [Tdrd6b (Chr20)](http://www.ensembl.org/Danio_rerio/Transcript/ProteinSummary?db=core;g=ENSDARG00000014039;r=20:42640658-42664630;t=ENSDART00000134066 )

- [Tdrd6c (Chr17)](http://www.ensembl.org/Danio_rerio/Gene/Summary?db=core;g=ENSDARG00000089954;r=17:6446863-6484305;t=ENSDART00000154540 )

The 2 on Chr20 (a+b) seem to be a gene duplication and tdrd6c (Chr17) was perhaps a result of genome duplication (before the gene duplication). As I said, things get weird in fish and that why removing duplicate genes is not ideal in this case.

>  Could you introduce a nice RNA-Seq dataset to play?

We have one from our lab which I could send you via email one our datasets. We have WT and mutant, 4 replicates, mRNA-seq. We think the mutated mutant is involved in the piRNA pathway, so it is likely that transposon expression is up. This is unpublished data, so I would you to keep it private. Just let me know if this would be ok.

**Comment by hyunhwaj** [comment]
Thanks for the explanation @adomingues, for the dataset, I can wait until the data is published, but at any time I may need the data to figure out a problem if we have one, and I will ask you to have the data at that time.

Thank you,

Hwan

**Comment by wjyzidane** [comment]
Hi Hyum-Hwan,

I have a quick question related to the reference. What does the specific number mean for the different repeats subfamily. Like HERV9, HERV15, what is the difference between the sequence of HERV9 and HERV15 and what is the rule they get these different number?

Thanks！
Jingyi

> 在 2018年1月23日，下午1:23，Jingyi Wu <wjyzidane@gmail.com> 写道：
> 
> Thanks Hyum-Hwan! I would give it a try!
> 
> Jingyi
> 
>

**Comment by hyunhwaj** [comment]
Hello @wjyzidane, I don't find any certain rules to distinguish those elements by different numbers. In case of the HERV family, it seems that  I have attached links to the information how they give names of the repeats, hope it helps you: https://www.nature.com/articles/nrg2165-c1

By the way, I am curious updates of `SalmonTE` (index building and new index) works for you well. Please let me know if you have any question.

P.S. I am sorry to say, but could you call my name as Hwan or Hyun-Hwan (my full name)? I am not glad to see the typo in my name because "Hyum-Hwan" sounds like "Disgusted Hwan" in my mother tongue 😅 I am sure you didn't intend the typo but want to tell you to tell my correct name later.

Best,

Hwan

**Comment by hyunhwaj** [comment]
Hello @wjyzidane, I don't find any certain rules to distinguish those elements by different numbers. In case of the HERV family, it seems that there are no straightforward rules for clarifications: [1](http://jvi.asm.org/content/77/19/10414/T2.expansion). I also have attached links to the information how they give names of the repeats, hope it helps you: [2](https://www.nature.com/articles/nrg2165-c1)

By the way, I am curious updates of SalmonTE (index building and new index) works for you well. Please let me know if you have any question.

P.S. I am sorry to say, but could you call my name as Hwan or Hyun-Hwan (my full name)? I am not glad to see the typo in my name because "Hyum-Hwan" sounds like "Disgusted Hwan" in my mother tongue 😅 I am sure you didn't intend the typo but want to tell you to tell my correct name later.

Best,

Hwan

**Comment by wjyzidane** [comment]
Hi Hwan,

I am so sorry for the typo in the previous post. It seems that my typo correct system automatically changes the spelling. I apologize for this unpleasant feeling it bought for you. 

I tried the mouse reference and it works well so far. Thanks so much for generating this reference and I would let you know if I find any problem in the future. Also thanks for the information about the ERV, I would look into it.

Best,
Jingyi

**Comment by hyunhwaj** [comment]
@wjyzidane It's fine, and you don't need to apologize 😃! I am glad to hear that the reference is working, and I'd rather close this issue. Please open another issue if you have.

Best Regards,

Hwan
